# Generated by Django 3.0.5 on 2020-05-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachable',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attachable',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
