# Generated by Django 3.0.5 on 2020-05-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200428_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='student', max_length=64),
            preserve_default=False,
        ),
    ]
