# Generated by Django 3.0.5 on 2020-05-19 16:51

from uuid import uuid4

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations, models
import django.db.models.deletion
    
def create_admin_person(apps, schema_editor):
    User = apps.get_model('users', 'User')

    user, is_created = User.objects.get_or_create(
        username='ovangle@gmail.com',
        email='ovangle@gmail.com',
        password=make_password('temp'),
        is_staff=True,
        is_superuser=True,
        defaults={
            'id': uuid4
        }
    )

    AdminPerson = apps.get_model('users', 'AdminPerson')
    person, is_created = AdminPerson.objects.get_or_create(
        email='ovangle@gmail.com',
        first_name='Thomas',
        surname='Stephenson',
        user_id=user.id,
        defaults={
            'id': uuid4
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200519_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPerson',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=1024)),
                ('first_name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_admin_person)
    ]
