# Generated by Django 3.0.4 on 2020-03-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_data_import_block_assessments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockassessmentattempt',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lessonoutcomeselfassessmentattempt',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lessonprelearningassessmentattempt',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unitassessmentattempt',
            options={},
        ),
        migrations.RemoveField(
            model_name='lessonprelearningassessmentattempt',
            name='completed',
        ),
        migrations.AddField(
            model_name='lessonprelearningassessmentattempt',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lessonoutcomeselfassessmentattempt',
            name='rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
