# Generated by Django 3.0.5 on 2020-04-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_auto_20200404_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='completionbasedreport',
            name='generation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ratingbasedreport',
            name='generation',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
