# Generated by Django 3.0.4 on 2020-03-30 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('assessments', '0005_blockassessmentreport_lessonoutcomeselfassessmentreport_lessonprelearningassessmentreport_markedasse'), ('assessments', '0006_lessonprelearningassessmentreport_most_recent_completion_at'), ('assessments', '0007_auto_20200328_0419'), ('assessments', '0008_lessonprelearningassessmentreport__completed_candidate_ids')]

    dependencies = [
        ('schools', '0007_auto_20200322_2131'),
        ('assessments', '0004_auto_20200327_0503'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkedAssessmentReport',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('total_candidate_count', models.IntegerField()),
                ('attempted_candidate_count', models.IntegerField()),
                ('_not_attempted_ids', models.TextField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.AssessmentSchema')),
                ('subject_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.SubjectClass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RatedAssessmentReport',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('total_candidate_count', models.IntegerField()),
                ('attempted_candidate_count', models.IntegerField()),
                ('_not_attempted_ids', models.TextField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.AssessmentSchema')),
                ('subject_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.SubjectClass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlockAssessmentReport',
            fields=[
                ('markedassessmentreport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessments.MarkedAssessmentReport')),
            ],
            options={
                'abstract': False,
            },
            bases=('assessments.markedassessmentreport',),
        ),
        migrations.CreateModel(
            name='LessonOutcomeSelfAssessmentReport',
            fields=[
                ('ratedassessmentreport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessments.RatedAssessmentReport')),
            ],
            options={
                'abstract': False,
            },
            bases=('assessments.ratedassessmentreport',),
        ),
        migrations.CreateModel(
            name='UnitAssessmentReport',
            fields=[
                ('markedassessmentreport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessments.MarkedAssessmentReport')),
            ],
            options={
                'abstract': False,
            },
            bases=('assessments.markedassessmentreport',),
        ),
        migrations.CreateModel(
            name='LessonPrelearningAssessmentReport',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('total_candidate_count', models.IntegerField()),
                ('attempted_candidate_count', models.IntegerField()),
                ('_not_attempted_ids', models.TextField()),
                ('completed_candidate_count', models.IntegerField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.AssessmentSchema')),
                ('subject_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.SubjectClass')),
                ('most_recent_completion_at', models.DateTimeField(null=True)),
                ('_completed_candidate_ids', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
