# Generated by Django 3.0.5 on 2020-05-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_auto_20200505_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completionbasedprogress',
            name='generation',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='completionbasedreport',
            name='generation',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gradedprogress',
            name='generation',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gradedreport',
            name='generation',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='passfailprogress',
            name='generation',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='passfailreport',
            name='generation',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ratedprogress',
            name='generation',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ratedreport',
            name='generation',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
