# Generated by Django 3.0.5 on 2020-04-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_data_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='completionbasedreport',
            name='_partially_completed_candidate_ids',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='completionbasedreport',
            name='partially_completed_candidate_count',
            field=models.IntegerField(null=True),
        ),
    ]
