# Generated by Django 3.0.5 on 2020-04-13 15:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_data_prepopulate_subject_tree'),
        ('schools', '0009_auto_20200404_0811'),
        ('assessments', '0008_auto_20200409_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionBasedProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('generation', models.PositiveIntegerField(default=0)),
                ('_assessment_ids', models.TextField()),
                ('_attempted_assessment_ids', models.TextField()),
                ('_complete_assessment_ids', models.TextField()),
                ('_partially_complete_assessment_ids', models.TextField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.SubjectNode')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RatingBasedProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('generation', models.PositiveIntegerField(default=0)),
                ('_assessment_ids', models.TextField()),
                ('_attempted_assessment_ids', models.TextField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.SubjectNode')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ratingbasedreport',
            name='_attempted_candidate_scores',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='StateMachineReport',
        ),
    ]
