# Generated by Django 3.0.5 on 2020-04-21 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '1003_auto_20200421_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratedreport',
            old_name='rating_std_deviation',
            new_name='rating_std_dev',
        ),
    ]
