# Generated by Django 3.0.5 on 2020-04-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '1004_auto_20200421_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentoptions',
            old_name='_RATED_max_available_rating',
            new_name='_ratedattempt_max_available_rating',
        ),
    ]
