# Generated by Django 3.0.4 on 2020-03-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_auto_20200323_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockassessmentattempt',
            options={'ordering': ('assessment_id', 'attempt_number')},
        ),
        migrations.AlterModelOptions(
            name='lessonoutcomeselfassessmentattempt',
            options={'ordering': ('assessment_id', 'attempt_number')},
        ),
        migrations.AlterModelOptions(
            name='lessonprelearningassessmentattempt',
            options={'ordering': ('assessment_id', 'attempt_number')},
        ),
        migrations.AlterModelOptions(
            name='unitassessmentattempt',
            options={'ordering': ('assessment_id', 'attempt_number')},
        ),
        migrations.RenameField(
            model_name='lessonoutcomeselfassessmentschema',
            old_name='lesson_outcome',
            new_name='lessonoutcome',
        ),
    ]
