# Generated by Django 3.0.4 on 2020-03-27 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_data_populate_subject_tree'),
        ('assessments', '0004_auto_20200326_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentschema',
            name='subject',
        ),
        migrations.AddField(
            model_name='assessmentschema',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.SubjectNode'),
        ),
    ]
