# Generated by Django 3.0.4 on 2020-03-27 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_data_add_node_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockassessmentschema',
            name='block',
        ),
        migrations.RemoveField(
            model_name='lessonoutcomeselfassessmentschema',
            name='lessonoutcome',
        ),
        migrations.RemoveField(
            model_name='lessonprelearningassessmentschema',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='unitassessmentschema',
            name='unit',
        ),
    ]
