# Generated by Django 3.0.4 on 2020-03-26 23:31

from django.db import migrations, models

def populate_premeth_tree(apps, schema_editor):
    Subject = apps.get_model('subjects', 'Subject')
    SubjectNode = apps.get_model('subjects', 'SubjectNode')



class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20200326_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectNode',
            fields=[
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('node_type', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
