# Generated by Django 3.0.5 on 2020-04-19 12:05

import api.subjects.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_data_prepopulate_subject_tree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectnode',
            name='node_type',
            field=api.subjects.models.SubjectNodeTypeField(),
        ),
    ]
