# Generated by Django 3.0.5 on 2020-05-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self', '0003_user_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_type',
            new_name='type',
        ),
    ]
