# Generated by Django 3.0.4 on 2020-03-20 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',     
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024))
            ]
        ),

        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=2048)),
                ('first_name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('student_code', models.CharField(max_length=16)),
                ('year_level', models.PositiveSmallIntegerField()),
                ('compass_number', models.PositiveSmallIntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School'))
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=2048)),
                ('first_name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('teacher_code', models.CharField(max_length=16)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School'))
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectClass',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('students', models.ManyToManyField(to='schools.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Teacher')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School'))
            ],
            options={
                'abstract': False,
            },
        ),
    ]
