# Generated by Django 3.0.4 on 2020-03-20 14:21

from uuid import uuid4

from django.db import migrations

from utils import importer

from utils.importer import (
	get_premeth_subject,
	get_tc_school
)

def create_schools(apps, schema_migration):
	School = apps.get_model('schools', 'School')

	tc_school = importer.schools.School.tc_school()
	db_school = School(
		id=tc_school.id,
		name=tc_school.name
	)
	db_school.save()

	create_teachers(apps)
	create_students(apps)

def create_students(apps):
	Student = apps.get_model('schools', 'Student')
	Student.objects.bulk_create(
		Student(
			id=import_student.id,
			school_id=get_tc_school(apps).id,
			first_name=import_student.first_name,
			surname=import_student.surname,
			email=import_student.code + '@tc.vic.edu.au',
			student_code=import_student.code,
			year_level=import_student.year_level,
			compass_number=import_student.compass_number
		) for import_student in importer.schools.Student.all()
	)
	print(f'{Student.objects.count()} students created.')

def create_teachers(apps):
	Teacher = apps.get_model('schools', 'Teacher')
	mvi = Teacher(
		id=uuid4(), 
		school_id=get_tc_school(apps).id,
		first_name='Matthew',
		surname='VICENDESE',
		teacher_code='MVI',
		email='mvi@tc.vic.edu.au'
	)
	mvi.save()
	eraw = Teacher(
		id=uuid4(),
		school_id=get_tc_school(apps).id,
		first_name='Unknown',
		surname='UNKNOWN',
		teacher_code='ERAW',
		email='eraw@tc.vic.edu.au'
	)
	eraw.save()
	print(f'{Teacher.objects.count()} teachers created')


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(create_schools)
    ]
