# Generated by Django 3.0.4 on 2020-03-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_data_import_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(max_length=1024),
        ),
    ]
