# Generated by Django 3.0.4 on 2020-03-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20200322_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectclass',
            name='subgroup',
            field=models.CharField(default='A', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectclass',
            name='year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
    ]
