# Generated by Django 3.0.4 on 2020-03-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_data_set_class_year_subgroup'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subjectclass',
            index=models.Index(fields=['-year', 'subject_id', 'subgroup'], name='schools_sub_year_2c87e3_idx'),
        ),
    ]
